export default {
  "code": 200,
  "msg": "成功",
  "data": {
    "total": 11,
    "list": [{
        "createDate": "2020-02-26",
        "creator": "韩韦",
        "updateDate": null,
        "modifier": null,
        "id": "1",
        "systemName": "HR权限管理",
        "systemCode": "PORTAL",
        "systemUrl": "",
        "flag": "Y",
        "bigIcon": "http://bdmp-potral.oss-cn-beijing.aliyuncs.com/portal_image/20210908/1631070443428644.png",
        "groupName": "2",
        "parentId": "0",
        "isBlank": 0,
        "isApp": 0,
        "externalPerssiom": "affiliation,brand,region,menu_dimession",
        "isAccept": null,
        "childrenVo": []
      },
      {
        "createDate": "2023-01-12",
        "creator": "涂晨光",
        "updateDate": null,
        "modifier": null,
        "id": "attendance-report",
        "systemName": "考勤管理",
        "systemCode": "attendance-report",
        "systemUrl": "https://retailr1.bellecdn.com/attendance-report-portal/index.html",
        "flag": "Y",
        "bigIcon": null,
        "groupName": "1",
        "parentId": "0",
        "isBlank": 0,
        "isApp": 0,
        "externalPerssiom": "org",
        "isAccept": null,
        "childrenVo": []
      },
      {
        "createDate": "2022-10-09",
        "creator": "林任耿",
        "updateDate": null,
        "modifier": null,
        "id": "pghsystem",
        "systemName": "系统",
        "systemCode": "pghsystem",
        "systemUrl": "https://hr-mdm-test.net.cn",
        "flag": "Y",
        "bigIcon": null,
        "groupName": "2",
        "parentId": "0",
        "isBlank": 0,
        "isApp": 0,
        "externalPerssiom": "region,brand,org",
        "isAccept": null,
        "childrenVo": []
      },
      {
        "createDate": "2022-09-23",
        "creator": "林任耿",
        "updateDate": null,
        "modifier": null,
        "id": "hr-dimission",
        "systemName": "离职管理",
        "systemCode": "hr-dimission",
        "systemUrl": "https://hr-dimission-testnet.cn/index.html",
        "flag": "Y",
        "bigIcon": null,
        "groupName": "2",
        "parentId": "pghsystem",
        "isBlank": 1,
        "isApp": 0,
        "externalPerssiom": "",
        "isAccept": null,
        "childrenVo": []
      },
      {
        "createDate": "2022-10-13",
        "creator": "杜海峰",
        "updateDate": null,
        "modifier": null,
        "id": "hr-entry",
        "systemName": "入职管理",
        "systemCode": "hr-entry",
        "systemUrl": "https://hr-entry-testnet.cn/",
        "flag": "Y",
        "bigIcon": null,
        "groupName": "2",
        "parentId": "0",
        "isBlank": 0,
        "isApp": 0,
        "externalPerssiom": "",
        "isAccept": null,
        "childrenVo": []
      },
      {
        "createDate": "2022-11-07",
        "creator": "杜海峰",
        "updateDate": null,
        "modifier": null,
        "id": "hr-personnel",
        "systemName": "花名册系统",
        "systemCode": "hr-personnel",
        "systemUrl": "https://s-testnet.cn/hr-personnel-test/",
        "flag": "Y",
        "bigIcon": null,
        "groupName": "2",
        "parentId": "pghsystem",
        "isBlank": 1,
        "isApp": 0,
        "externalPerssiom": "",
        "isAccept": null,
        "childrenVo": []
      },
      {
        "createDate": "2022-09-27",
        "creator": "林任耿",
        "updateDate": null,
        "modifier": null,
        "id": "hr-report",
        "systemName": "报表中心",
        "systemCode": "hr-report",
        "systemUrl": "https://office-data-imports-tool-testnet.cn/",
        "flag": "Y",
        "bigIcon": null,
        "groupName": "2",
        "parentId": "pghsystem",
        "isBlank": 0,
        "isApp": 0,
        "externalPerssiom": "salary_org",
        "isAccept": null,
        "childrenVo": []
      },
      {
        "createDate": "2023-01-09",
        "creator": "李清",
        "updateDate": null,
        "modifier": null,
        "id": "hr-softsail",
        "systemName": "帆软集成",
        "systemCode": "hr-softsail",
        "systemUrl": "https://hr-softsail-testnet.cn/",
        "flag": "Y",
        "bigIcon": null,
        "groupName": "2",
        "parentId": "pghsystem",
        "isBlank": 0,
        "isApp": 0,
        "externalPerssiom": "",
        "isAccept": null,
        "childrenVo": []
      },
      {
        "createDate": "2022-10-24",
        "creator": "卢明川",
        "updateDate": null,
        "modifier": null,
        "id": "hrmdm",
        "systemName": "组织管理",
        "systemCode": "hrmdm",
        "systemUrl": "https://hr-mdm-testnet.cn",
        "flag": "Y",
        "bigIcon": null,
        "groupName": "1",
        "parentId": "pghsystem",
        "isBlank": 0,
        "isApp": 0,
        "externalPerssiom": "",
        "isAccept": null,
        "childrenVo": []
      },
      {
        "createDate": "2023-01-11",
        "creator": "涂晨光",
        "updateDate": null,
        "modifier": null,
        "id": "new-bi",
        "systemName": "帆软报表",
        "systemCode": "new-bi",
        "systemUrl": "https://new-binet.cn",
        "flag": "Y",
        "bigIcon": null,
        "groupName": "1",
        "parentId": "pghsystem",
        "isBlank": 0,
        "isApp": 0,
        "externalPerssiom": "",
        "isAccept": null,
        "childrenVo": []
      },
      {
        "createDate": "2022-11-09",
        "creator": "涂晨光",
        "updateDate": null,
        "modifier": null,
        "id": "RecruitmentManagement",
        "systemName": "招聘管理",
        "systemCode": "RecruitmentManagement",
        "systemUrl": "https://hr-dimission-testnet.cn/index.html",
        "flag": "Y",
        "bigIcon": null,
        "groupName": "2",
        "parentId": "pghsystem",
        "isBlank": 0,
        "isApp": 0,
        "externalPerssiom": "",
        "isAccept": null,
        "childrenVo": []
      }
    ],
    "pageNum": 1,
    "pageSize": 50,
    "size": 11,
    "startRow": 1,
    "endRow": 11,
    "pages": 1,
    "prePage": 0,
    "nextPage": 0,
    "isFirstPage": true,
    "isLastPage": true,
    "hasPreviousPage": false,
    "hasNextPage": false,
    "navigatePages": 8,
    "navigatepageNums": [
      1
    ],
    "navigateFirstPage": 1,
    "navigateLastPage": 1
  }
}